name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@5.1
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Pharo64-stable'
      - uses: BerniWittmann/background-server-action@latest
        with:
          command: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
          start: ./test/xtdb.sh
        timeout-minutes: 15
